name: Continuous Integration

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-x86_64-unknown-linux-musl-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-x86_64-unknown-linux-musl-

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl

      - run: cargo install --force cargo-deb

      - name: "Find version"
        if: startsWith(github.ref, 'refs/tags/')
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: image
          tags: type=semver,pattern={{version}}

      - name: "Adjust version number in Cargo.toml"
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          sed -i'' "s/0\\.0\\.0-git/${{ steps.meta.outputs.version }}/" Cargo.toml
          sed -i'' "s/0\\.0\\.0-git/${{ steps.meta.outputs.version }}/" Cargo.lock

      - name: "Build project for VyOS"
        run: cargo build --target x86_64-unknown-linux-musl --release

      - name: "Build debian package"
        run: cargo deb --no-build --no-strip --target x86_64-unknown-linux-musl

      - name: "Rename artifacts"
        run: |
          mv target/x86_64-unknown-linux-musl/release/wpm-api-vyos .
          mv target/x86_64-unknown-linux-musl/debian/wpm-api-vyos_*_amd64.deb .

      - name: "Upload artifacts"
        uses: actions/upload-artifact@v3
        with:
          name: vyos-wpm-api
          path: |
            wpm-api-vyos
            wpm-api-vyos_*_amd64.deb

      - uses: crazy-max/ghaction-github-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            wpm-api-vyos
            wpm-api-vyos_*_amd64.deb
