name: Continuous Integration

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build project for VyOS
        run: |
          rustup target add x86_64-unknown-linux-musl        
          cargo build --target x86_64-unknown-linux-musl --release

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: vyos-wpm-api
          path: target/x86_64-unknown-linux-musl/release/wpm-api-vyos
